version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=auth-service:50051
      - CODEGEN_SERVICE_URL=codegen-service:50052
      - PROJECT_SERVICE_URL=project-service:50053
      - DEPLOYMENT_SERVICE_URL=deployment-service:50059
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
    external: true
