version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - CODEGEN_SERVICE_URL=${CODEGEN_SERVICE_URL}
      - PROJECT_SERVICE_URL=${PROJECT_SERVICE_URL}
      - DEPLOYMENT_SERVICE_URL=${DEPLOYMENT_SERVICE_URL}
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 
    external: true
