name: Build and Deploy API Gateway

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'src/**'
  workflow_dispatch: # Manual trigger option

env:
  AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
  CODEGEN_SERVICE_URL: ${{ secrets.CODEGEN_SERVICE_URL }}
  PROJECT_SERVICE_URL: ${{ secrets.PROJECT_SERVICE_URL }}
  DEPLOYMENT_SERVICE_URL: ${{ secrets.DEPLOYMENT_SERVICE_URL }}

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: Dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure app-network exists
        run: |
          if ! docker network inspect app-network >/dev/null 2>&1; then
            echo "Creating app-network..."
            docker network create app-network
          else
            echo "app-network already exists."
          fi

      - name: Build and deploy with docker-compose
        run: |
          # Stop existing container if running
          docker-compose down api-gateway || true
          
          # Build and start the service
          docker-compose up -d --build api-gateway

      - name: Verify deployment
        run: |
          # Wait for service to start
          echo "Waiting for service to start..."
          sleep 10
          
          # Check if container is running
          if ! docker ps | grep -q api-gateway; then
            echo "Error: Container is not running!"
            docker logs api-gateway
            exit 1
          fi
          
          echo "✅ API Gateway deployment successful!"

      - name: Cleanup
        if: always()
        run: |
          # Remove dangling images to save disk space
          docker image prune -f