name: Deploy API Gateway

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: smartapiforge/api-gateway:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/api-gateway
            git pull
            
            # Set environment variables for microservices
            export AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }}
            export CODEGEN_SERVICE_URL=${{ secrets.CODEGEN_SERVICE_URL }}
            export PROJECT_SERVICE_URL=${{ secrets.PROJECT_SERVICE_URL }}
            export DEPLOYMENT_SERVICE_URL=${{ secrets.DEPLOYMENT_SERVICE_URL }}
            
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
            docker system prune -af 